Feature/dtserwthre 262 custom headers
hyperwallet/hyperwallet-ios-sdk pull request #103
Opened 2020-11-16 22:29 UTC by ddhar-hw

2020-11-17 14:09 UTC, aparthibanpaypal submitted a review, later dismissed

2020-11-17 16:35 UTC, pdamodarannair approved these changes

2020-11-18 18:25 UTC, jsaini-hw requested changes

2020-11-18 19:04 UTC, ddhar-hw commented on Sources/HTTPTransaction.swift
> +        return info["CFBundleShortVersionString"] as? String ?? "Unknown"
Good catch!! Thanks!

2020-11-18 19:07 UTC, ddhar-hw commented on Sources/HTTPTransaction.swift
> +        let deviceName = UIDevice.current.name
This one I was not sure what was the intent - the ticket says `deviceName` - which made me believe we want to see the unique device that made the request and not just the model name. Can you confirm we want to display the model here

2020-11-18 19:14 UTC, ddhar-hw commented on Sources/HTTPTransaction.swift
> +        let deviceName = UIDevice.current.name
Now that I think about this more - think model makes more sense. Will update

2020-11-19 02:31 UTC, jsaini-hw approved these changes

2020-11-20 17:40 UTC, jsaini-hw approved these changes

2020-11-20 21:07 UTC, jsaini-hw approved these changes

2020-11-20 21:18 UTC, malaw-hw approved these changes

2020-11-20 21:19 UTC, merged